### ISSUE TITLE
1975 rainfall

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/temp-manu#2]
https://github.com/tbep-tech/temp-manu/blob/74a1b1935c5ce08742006bd8ea6691e9927c31ce/manu-draft.qmd#L173

avg annual rainfall hasn't really changed over the period of record tho, no? it is a bit misleading to reference 1975 as a baseline since it was a significant drought (see usgs records, https://pubs.usgs.gov/wri/1978/0029/report.pdf for example)

**Comment by emseabee** [comment]
might also want to acknowledge ENSO (el nino/la nina) in relation to the precip anomolies identified in the last sentence.

**Comment by esherwoo77** [comment]
@fawda123 : Here's the DISTRICT website where USGS basin summaries across the region can be accessed back to 1915: https://www.swfwmd.state.fl.us/resources/data-maps/rainfall-summary-data-region . I would argue that these basin-wide summaries are the most representative precip information for our region.

**Comment by fawda123** [comment]
Thanks @esherwoo77, I found that earlier this morning https://tbep-tech.github.io/tbep-os-presentations/state_of_the_bay_2023.html#/rain-as-a-driver
